services:
  sqldb-test:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d postgres -c 'SELECT 1;'"]
      interval: 3s
      timeout: 3s
      retries: 5

  association-test:
    image: ${DOCKER_REGISTRY-}association
    build:
      context: .
      dockerfile: src/Services/Association/Association/Dockerfile
    depends_on:
      sqldb-test:
        condition: service_healthy

  url-test:
    image: ${DOCKER_REGISTRY-}url
    build:
      context: .
      dockerfile: src/Services/Url/Url/Dockerfile
    depends_on:
      sqldb-test:
        condition: service_healthy
