services:
  sqldb-test:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d postgres -c 'SELECT 1;'"]
      interval: 3s
      timeout: 3s
      retries: 5
