services:
  sqldb:
    image: postgres:18-alpine
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d postgres -c 'SELECT 1;'"]
      interval: 3s
      timeout: 3s
      retries: 5

  association:
    image: ${DOCKER_REGISTRY-}association
    build:
      context: .
      dockerfile: src/Services/Association/Association/Dockerfile
    depends_on:
      sqldb:
        condition: service_healthy

  url:
    image: ${DOCKER_REGISTRY-}url
    build:
      context: .
      dockerfile: src/Services/Url/Url/Dockerfile
    depends_on:
      sqldb:
        condition: service_healthy

  apigateway.web:
    image: ${DOCKER_REGISTRY-}apigatewayweb
    build:
      context: .
      dockerfile: src/ApiGateway.Web/Dockerfile
