services:
  etcd:
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"

  sqldb:
    environment:
      - POSTGRES_PASSWORD=postgres

  association:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=Host=sqldb;Database=Associations;Username=postgres;Password=postgres
      - EtcdConnectionString=http://etcd:2379
      - GrpcPort=81
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  url:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=Host=sqldb;Database=Associations;Username=postgres;Password=postgres
      - GrpcPort=81
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  apigateway.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - GrpcUrls__AssociationService=http://association:81
      - GrpcUrls__UrlService=http://url:81
    ports:
      - "8080:80"
    volumes:
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro
