// <auto-generated />
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniUrl.KeyManager.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniUrl.KeyManager.Infrastructure.Migrations
{
    [DbContext(typeof(KeysManagerContext))]
    partial class KeysManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniUrl.KeyManager.Domain.Models.Configuration", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<JsonDocument>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Key");

                    b.ToTable("Configuration", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Configuration");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MiniUrl.KeyManager.Domain.Models.Key", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Keys", (string)null);
                });

            modelBuilder.Entity("MiniUrl.KeyManager.Domain.Models.KeysGeneratorConfiguration", b =>
                {
                    b.HasBaseType("MiniUrl.KeyManager.Domain.Models.Configuration");

                    b.HasDiscriminator().HasValue("KeysGeneratorConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
